### ISSUE TITLE
Why did you delete https://replit.com/safariminer/solanum ?

### ISSUE THREAD

**Issue by hello-smile6** [Safariminer/safariminer#1]
Why?
I'm https://replit.com/@9pfs , by the way.

**Comment by Safariminer** [comment]
Because, not only am I less interested in IRC, Replit is not a decent hosting solution for what I wanted to do, so I closed the server and will close all other IRC servers I have made. The problem with the Solanum solution you provided is that I wanted, quite frankly, to replace my Discord server entirely with an IRC accessible from a Wii U, though Solanum requires many steps to connect to from a PC native client. It would've been impractical to host a websocat on a laptop and tunnel it through ngrok, compared to just using the laptop. That doesn't mean Wii U is practical to begin with, and that doesn't mean I won't return to IRC, but if I do return to IRC it won't be on Replit; it will be on a home-hosted or paid server.

**Comment by hello-smile6** [comment]
> Because, not only am I less interested in IRC, Replit is not a decent hosting solution for what I wanted to do, so I closed the server and will close all other IRC servers I have made. The problem with the Solanum solution you provided is that I wanted, quite frankly, to replace my Discord server entirely with an IRC accessible from a Wii U, though Solanum requires many steps to connect to from a PC native client. It would've been impractical to host a websocat on a laptop and tunnel it through ngrok, compared to just using the laptop. That doesn't mean Wii U is practical to begin with, and that doesn't mean I won't return to IRC, but if I do return to IRC it won't be on Replit; it will be on a home-hosted or paid server.

You could use your own server.

**Comment by hello-smile6** [comment]
Sorry I broke your server, I was trying to get it to stop connecting to mine.

**Comment by hello-smile6** [comment]
Also, it isn't a "solution". Solanum is open-source software. https://solanum.chat/

**Comment by Safariminer** [comment]
OI @hello-smile6 STOP BOMBARDING ME WITH MESSAGES WHEN I ALREADY SAID I DON'T GIVE A DAMN FUCK ANYMORE.
